language: python

matrix:
    include:
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true

cache: pip

install:
  - pip

script:
  - python -m tests.configTest
