version: 2
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  build:
    working_directory: ~/config-reader-python3
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          keys:
            - v{{ .Environment.CACHE_VERSION }}-dep-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - v{{ .Environment.CACHE_VERSION }}-dep-cache-{{ .Branch }}-
            - v{{ .Environment.CACHE_VERSION }}-dep-cache-
      - run:
          command: |
            pipenv --rm
            pip install --user pipenv
            pipenv install
      - save_cache:
          paths:
            - ".venv"
            - ~/.local/share/virtualenvs/
          key: v{{ .Environment.CACHE_VERSION }}-dep-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pipenv run "pytest"
  deploy:
    working_directory: ~/config-reader-python3
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          keys:
            - v{{ .Environment.CACHE_VERSION }}-dep-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - v{{ .Environment.CACHE_VERSION }}-dep-cache-{{ .Branch }}-
            - v{{ .Environment.CACHE_VERSION }}-dep-cache-
      - run:
          command: |
            pipenv --rm
            pip install --user pipenv
            pipenv install
      - save_cache:
          paths:
            - ".venv"
            - ~/.local/share/virtualenvs/
          key: v{{ .Environment.CACHE_VERSION }}-dep-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: verify git tag vs. version
          command: |
            pipenv run python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            pipenv run python setup.py sdist bdist_wheel
      - run:
          name: upload to pypi
          command: |
            pipenv install --skip-lock twine
            pipenv run twine upload dist/*
